### ISSUE TITLE
People feeling neutral shouldn't lead to game over

### ISSUE THREAD

**Issue by caryoscelus** [spirulence/power-department-ld38#31]
Not sure if it's fixed in post-jam version, but it seems to be true for jam.

Perhaps it can be left for hard mode, but i wonder if it's even playable at this point.

**Comment by spirulence** [comment]
You're right in that it is a very crude happiness mechanic. Right now the situation is:

- calculate a moving average of window size 3 of the unconnectedness of people
- if the latest is more connected than that average, +15 happiness

then

- reduce happiness by one point for every ten unreliable connectedness

then

- move happiness towards 35 (not up to par) by %25 percent

then

- if the average happiness over a window of size 5 is below 38, you lose

which essentially means you can have an immediate happiness dip that's not reported causing you to lose.

A crude fix would be to make the 'you lose' threshold lower, like 15 or 20. A more robust fix would be to revamp the whole system to make it more obvious why people are unhappy. What would you suggest?

I've included the relevant code. This is lines 397:436 of `app/src/state/Main.ts`.

```typescript
private updateHappiness() {
        this.demand.calculateSatisfaction();
        this.satisfactionHistory.push(this.demand.satisfaction);

        if(this.satisfactionHistory.length > 3){
            this.satisfactionHistory.shift();
        }

        let unconnectedSum = 0;
        for(let satisfaction of this.satisfactionHistory){
            unconnectedSum += satisfaction.unconnected;
        }
        let unconnectedAverage = unconnectedSum/this.satisfactionHistory.length;
        if(this.demand.satisfaction.unconnected < unconnectedAverage){
            this.happiness += 15;
        }

        for(let event of this.lastEvents){
            if(event.outage){
                this.happiness -= 15;
            }
        }

        this.happiness -= Math.floor(this.demand.satisfaction.unreliable / 10);

        this.happiness = this.happiness * 0.75 + 35.0 * 0.25;
        this.happinessHistory.push(this.happiness);
        if(this.happinessHistory.length > 5){
            this.happinessHistory.shift();
        }

        let sum = this.happinessHistory.reduce(function(a, b){return a+b});
        let average = sum / this.happinessHistory.length;
        if(average < 38.0){
            this.gameOver("People were unhappy with you for too long.");
            return true;
        }

        return false;
    }
```

**Comment by caryoscelus** [comment]
I would suggest `if(average < 38.0 && this.happinessHistory[3] < HAPPINESS_NEUTRAL && this.happinessHistory[4] < HAPPINESS_NEUTRAL)` and also show final happiness level on game over screen.

**Comment by spirulence** [comment]
Great suggestion! Included in 'must-fix-before-judging'.
