### ISSUE TITLE
Replace "base layer" with more visible grid

### ISSUE THREAD

**Issue by caryoscelus** [spirulence/power-department-ld38#32]
This should help people understand that mechanics are tile-based and thus how close should they build stations.

Could be done by simply adding another tiled layer.

**Comment by caryoscelus** [comment]
Wasn't really fixed. It appears we need to add layers in code as well as map files.

**Comment by spirulence** [comment]
Yes. Do you need any further guidance from me on how to do that?

**Comment by caryoscelus** [comment]
Perhaps lead me to the appropriate docs :) Even though i think i might figure out this one without them..

**Comment by caryoscelus** [comment]
Hmm, it seems to be auto-closed by mistake due to rebase.

**Comment by spirulence** [comment]
Fixed in #48
