### ISSUE TITLE
Clarify licensing on per-file basis and migrate to AGPLv3+

### ISSUE THREAD

**Issue by caryoscelus** [spirulence/power-department-ld38#57]

**Comment by spirulence** [comment]
A little history for posterity: 

This code began life as an extension of an example using TypeScript, Phaser, and Webpack. [https://github.com/geowarin/phaser-webpack](url)

That repository is licensed under MIT - and significant portions of this repo still mirror the structure of that one, although all the included dependencies were updated to modern versions, and the total LOC is at least 10x higher now.

We'd like to place the additional work (new files) in this repository under the AGPL to prevent other people from doing something with this code without releasing the source. So, we're going to put license information into each file. Some files will remain MIT - others will be AGPLv3+.

**Comment by spirulence** [comment]
@caryoscelus we should probably discuss how to license graphics, music, video, and other assets.

**Comment by caryoscelus** [comment]
> Some files will remain MIT - others will be AGPLv3+.

Or rather, they'll be double-licensed, i guess.

As for assets, i would go with CC-BY-SA unless there are any reasons to do otherwise.

**Comment by spirulence** [comment]
> Or rather, they'll be double-licensed, i guess.

I'll leave that detail to you, I didn't know this was an advantageous thing to do.

> CC-BY-SA

Great idea! Can you take care of doing that properly as well?

**Comment by caryoscelus** [comment]
>I'll leave that detail to you, I didn't know this was an advantageous thing to do.

From purely legal point of view, it might be not (though i think it is: we don't really need to put the whole file under mit, it's just that we place header there for convenience), but at the very least it will convey our intention.

>Can you take care of doing that properly as well?

Sure!
